name: Build

on:
  push:
    branches-ignore: [master, develop]
  pull_request:
    branches-ignore: [master, develop]

jobs:
  build:
    name: Build
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v1

    - name: Install Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make

    - name: Generate with Publish
      run: publish generate
