name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy with Publish
      run: swift run

    - name: Deploy Content
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: GITHUB_USER_NAME/GITHUB_USER_NAME.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./Output
      with:
        commitMessage: ${{ github.event.head_commit.message }}

    - name: Clear cache
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE/purge_cache" \
          -H "X-Auth-Email: $CF_API_EMAIL" \
          -H "X-Auth-Key: $CF_API_KEY" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
      env:
        CF_ZONE: ${{ secrets.CF_ZONE }}
        CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
