name: Jekyll site CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install bundler
      run: |
        sudo gem install bundler
        bundle install
        
    - name: Build with Jekyll
      run: bundle exec jekyll build
    
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master
        build_dir: _site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clear cache
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE/purge_cache" \
          -H "X-Auth-Email: $CF_API_EMAIL" \
          -H "X-Auth-Key: $CF_API_KEY" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
