name: Jekyll site CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Build with Jekyll
      run: bundle exec jekyll build
    
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: master